## Data Preprocessing

In [1]:
# importing libraries
import warnings
warnings.simplefilter('ignore')
import pandas as pd
import numpy as np

In [2]:
# read data csv files
deliverydf = pd.read_csv('../data/deliveries_data.csv')
matchdf = pd.read_csv('../data/match_data.csv')

In [3]:
matchdf.match_id = matchdf.match_id.astype(int)
matchdf.head()

,city,dates,host_team,match_id,player_of_match,result,season,toss_decision,toss_winner,venue,visiting_team,winner
0,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders
1,Chandigarh,2008-04-19,Kings XI Punjab,2,MEK Hussey,1,2008,bat,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Chennai Super Kings
2,Delhi,2008-04-19,Delhi Daredevils,3,MF Maharoof,1,2008,bat,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,Delhi Daredevils
3,Kolkata,2008-04-20,Kolkata Knight Riders,4,DJ Hussey,1,2008,bat,Deccan Chargers,Eden Gardens,Deccan Chargers,Kolkata Knight Riders
4,Mumbai,2008-04-20,Mumbai Indians,5,MV Boucher,1,2008,bat,Mumbai Indians,Wankhede Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore

In [4]:
deliverydf.wicket = deliverydf.wicket.astype(int)
deliverydf.match_id = deliverydf.match_id.astype(int)
deliverydf.head()

,ball,batsman,batsman_runs,batting_team,bowler,bowling_team,extras_runs,match_id,non_striker,over,total_runs,wicket,wicket_fielders,wicket_kind,wicket_player_out
0,1,SC Ganguly,0,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,1,1,BB McCullum,0,1,0,NaN,NaN,NaN
1,2,BB McCullum,0,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,0,1,SC Ganguly,0,0,0,NaN,NaN,NaN
2,3,BB McCullum,0,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,1,1,SC Ganguly,0,1,0,NaN,NaN,NaN
3,4,BB McCullum,0,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,0,1,SC Ganguly,0,0,0,NaN,NaN,NaN
4,5,BB McCullum,0,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,0,1,SC Ganguly,0,0,0,NaN,NaN,NaN

In [5]:
#sum of missing values in each column
matchdf.isnull().sum()

city               43
dates               0
host_team           0
match_id            0
player_of_match     4
result              0
season              0
toss_decision       0
toss_winner         0
venue               0
visiting_team       0
winner              0
dtype: int64

In [6]:
#sum of missing values in each column
deliverydf.isnull().sum()

ball                      0
batsman                   0
batsman_runs              0
batting_team              0
bowler                    0
bowling_team              0
extras_runs               0
match_id                  0
non_striker               0
over                      0
total_runs                0
wicket                    0
wicket_fielders      183473
wicket_kind          180802
wicket_player_out    180802
dtype: int64

In [7]:
# replace value
matchdf = matchdf.replace({'Rising Pune Supergiant':'Rising Pune Supergiants','Delhi Daredevils':'Delhi Capitals'})
deliverydf = deliverydf.replace({'Rising Pune Supergiant':'Rising Pune Supergiants','Delhi Daredevils':'Delhi Capitals'})

In [8]:
#merge season value from the matches dataframe to deliveries
data = matchdf.merge(deliverydf, left_on = 'match_id', right_on = 'match_id', how = 'left')

In [9]:
data.head()

,city,dates,host_team,match_id,player_of_match,result,season,toss_decision,toss_winner,venue,...,bowler,bowling_team,extras_runs,non_striker,over,total_runs,wicket,wicket_fielders,wicket_kind,wicket_player_out
0,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,P Kumar,Royal Challengers Bangalore,1,BB McCullum,0,1,0,NaN,NaN,NaN
1,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,P Kumar,Royal Challengers Bangalore,0,SC Ganguly,0,0,0,NaN,NaN,NaN
2,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,P Kumar,Royal Challengers Bangalore,1,SC Ganguly,0,1,0,NaN,NaN,NaN
3,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,P Kumar,Royal Challengers Bangalore,0,SC Ganguly,0,0,0,NaN,NaN,NaN
4,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,P Kumar,Royal Challengers Bangalore,0,SC Ganguly,0,0,0,NaN,NaN,NaN

In [10]:
# team percentage of matches won out of total matches played

df = data
# team matches played
team_matches_played = df.groupby(['match_id','batting_team'])['total_runs'].sum().reset_index()
team_matches_played['count']=1
team_matches_played = team_matches_played.groupby(['batting_team'])['count'].sum().reset_index()

# team innings win
df = matchdf[(matchdf.result==1)|(matchdf.result==2)]
df['match_wins'] = 1
team_matches_win = df.groupby(['winner'])['match_wins'].sum().reset_index()
team_matches_win = team_matches_win.merge(team_matches_played, left_on='winner', right_on='batting_team',how='left')
team_matches_win.rename(columns={'winner':'team','count':'matches_played'},inplace=True)
team_matches_win.drop(['batting_team'],axis=1,inplace=True)

# team win percentage
team_win_percentage = team_matches_win
team_win_percentage['win%'] = (team_win_percentage['match_wins']/team_win_percentage['matches_played'])*100
team_win_percentage.sort_values(ascending=False,by='win%')

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

                           team  match_wins  matches_played       win%
0           Chennai Super Kings         104             176  59.090909
7                Mumbai Indians         116             198  58.585859
12          Sunrisers Hyderabad          62             119  52.100840
6         Kolkata Knight Riders          98             190  51.578947
9              Rajasthan Royals          80             158  50.632911
10      Rising Pune Supergiants          15              30  50.000000
11  Royal Challengers Bangalore          91             191  47.643979
4               Kings XI Punjab          88             188  46.808511
2                Delhi Capitals          84             188  44.680851
3                 Gujarat Lions          13              30  43.333333
5          Kochi Tuskers Kerala           6              14  42.857143
1               Deccan Chargers          29              75  38.666667
8                 Pune Warriors          12              45  26.666667

In [11]:
# add new column won% of batting team and bowling team
team_win_percentage.rename(columns={'team':'batting_team','win%':'batting_team_won%'},inplace=True)
data = data.merge(team_win_percentage[['batting_team','batting_team_won%']],left_on='batting_team',right_on='batting_team',how='left')
team_win_percentage.rename(columns={'batting_team':'bowling_team','batting_team_won%':'bowling_team_won%'},inplace=True)
data = data.merge(team_win_percentage[['bowling_team','bowling_team_won%']],left_on='bowling_team',right_on='bowling_team',how='left')

data.tail()

,city,dates,host_team,match_id,player_of_match,result,season,toss_decision,toss_winner,venue,...,extras_runs,non_striker,over,total_runs,wicket,wicket_fielders,wicket_kind,wicket_player_out,batting_team_won%,bowling_team_won%
190142,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,0,Mandeep Singh,18,0,1,['M Prasidh Krishna'],caught,CH Gayle,46.808511,51.578947
190143,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,0,Mandeep Singh,18,0,0,NaN,NaN,NaN,46.808511,51.578947
190144,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,0,Mandeep Singh,18,1,0,NaN,NaN,NaN,46.808511,51.578947
190145,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,0,N Pooran,18,1,0,NaN,NaN,NaN,46.808511,51.578947
190146,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,0,Mandeep Singh,18,1,0,NaN,NaN,NaN,46.808511,51.578947

In [12]:
# calculate final score of team
df = data
final_score = df.groupby(['match_id','batting_team'])['total_runs'].sum().reset_index()
final_score.rename(columns={'total_runs':'final_score'},inplace=True)
inning1 = final_score[final_score.index%2==0]
inning1['inning']=1
inning2 = final_score[final_score.index%2!=0]
inning2['inning']=2
inningdf = pd.concat([inning1,inning2],axis=0)

# inning 1 & 2 data
new_data = data.merge(inningdf,left_on=['match_id','batting_team'],right_on=['match_id','batting_team'],how='left')
new_data.head()

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,city,dates,host_team,match_id,player_of_match,result,season,toss_decision,toss_winner,venue,...,over,total_runs,wicket,wicket_fielders,wicket_kind,wicket_player_out,batting_team_won%,bowling_team_won%,final_score,inning
0,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,1,0,NaN,NaN,NaN,51.578947,47.643979,222,1
1,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1
2,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,1,0,NaN,NaN,NaN,51.578947,47.643979,222,1
3,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1
4,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1

In [13]:
# rename the column match_id to id
new_data.rename(columns={'match_id':'id'},inplace=True)
new_data

,city,dates,host_team,id,player_of_match,result,season,toss_decision,toss_winner,venue,...,over,total_runs,wicket,wicket_fielders,wicket_kind,wicket_player_out,batting_team_won%,bowling_team_won%,final_score,inning
0,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,1,0,NaN,NaN,NaN,51.578947,47.643979,222,1
1,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1
2,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,1,0,NaN,NaN,NaN,51.578947,47.643979,222,1
3,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1
4,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,0,0,0,NaN,NaN,NaN,51.578947,47.643979,222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190142,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,18,0,1,['M Prasidh Krishna'],caught,CH Gayle,46.808511,51.578947,150,1
190143,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,18,0,0,NaN,NaN,NaN,46.808511,51.578947,150,1
190144,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,18,1,0,NaN,NaN,NaN,46.808511,51.578947,150,1
190145,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,18,1,0,NaN,NaN,NaN,46.808511,51.578947,150,1
190146,NaN,2020-10-26 00:00:00,Kolkata Knight Riders,802,CH Gayle,1,2020,field,Kings XI Punjab,Sharjah Cricket Stadium,...,18,1,0,NaN,NaN,NaN,46.808511,51.578947,150,1

In [14]:
result=new_data

In [15]:
result.bowling_team.unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Chennai Super Kings', 'Delhi Capitals',
       'Rajasthan Royals', 'Deccan Chargers', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions'], dtype=object)

In [16]:
# Keeping only consistent teams
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Capitals', 'Sunrisers Hyderabad']

result = result[(result['batting_team'].isin(consistent_teams)) & (result['bowling_team'].isin(consistent_teams))]

In [28]:
dataset = result

number_of_time_win_match = dict()

for team1 in consistent_teams:
  for team2 in consistent_teams:
    if team1!=team2:
      set1 = (team1, team2)
      set1 = str(set1)
      if set1 not in number_of_time_win_match:
        number_of_time_win_match[set1] = dict()
        number_of_time_win_match[set1]['team1']=0
        number_of_time_win_match[set1]['team2']=0

id = 0
inning = 0
for id1, inn ,batting_team, bowling_team, winner in zip(dataset.id, dataset.inning, dataset.batting_team, dataset.bowling_team, dataset.winner):
  if (id!=id1 and inning!=inn) or (id==id1 and inning!=inn):
    set1 = (batting_team, bowling_team)
    set1 = str(set1)
    if batting_team==winner:
      number_of_time_win_match[set1]['team1']+=1
    elif bowling_team==winner:
      number_of_time_win_match[set1]['team2']+=1
    id = id1
    inning = inn

import json
with open('../data/num_of_time_win_match.json', 'w') as fp:
    json.dump(number_of_time_win_match, fp)

In [19]:
# add new column in dataset

dataset = result

number_of_time_batting_team_win = []
number_of_time_bowling_team_win = []

for batting_team, bowling_team in zip(dataset.batting_team, dataset.bowling_team):
  set1 = (batting_team, bowling_team)
  set1 = str(set1)
  number_of_time_batting_team_win.append(number_of_time_win_match[set1]['team1'])
  number_of_time_bowling_team_win.append(number_of_time_win_match[set1]['team2'])

dataset['number_of_time_batting_team_win'] = number_of_time_batting_team_win
dataset['number_of_time_bowling_team_win'] = number_of_time_bowling_team_win

result = dataset

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [20]:
# create new column for current score
score = [result.total_runs[0]]
id = 1
inning = 1
for run,ids,innings in zip(result.total_runs[1:], result.id[1:], result.inning[1:]):
    if ids==id and innings==inning:
        score.append(run+score[-1])
    else:
        score.append(run)
        id=ids
        inning=innings
result["score"] = score

result.head()

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

,city,dates,host_team,id,player_of_match,result,season,toss_decision,toss_winner,venue,...,wicket_fielders,wicket_kind,wicket_player_out,batting_team_won%,bowling_team_won%,final_score,inning,number_of_time_batting_team_win,number_of_time_bowling_team_win,score
0,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,NaN,NaN,NaN,51.578947,47.643979,222,1,11,8,1
1,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,NaN,NaN,NaN,51.578947,47.643979,222,1,11,8,1
2,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,NaN,NaN,NaN,51.578947,47.643979,222,1,11,8,2
3,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,NaN,NaN,NaN,51.578947,47.643979,222,1,11,8,2
4,Bangalore,2008-04-18,Royal Challengers Bangalore,1,BB McCullum,1,2008,field,Royal Challengers Bangalore,M Chinnaswamy Stadium,...,NaN,NaN,NaN,51.578947,47.643979,222,1,11,8,2

In [21]:
# convert player name to general format

player = [result.batsman[0],result.non_striker[0]]
id = 1
inning = 1
for id1, inning1, batsman, non_striker, index in zip(result.id, result.inning, result.batsman, result.non_striker, result.index):
    
    if (id==id1 and inning==inning1):
        
        if batsman in player:
            n = player.index(batsman)+1
            result.batsman[index]='player'+str(n)
        else:
            player.append(batsman)
            n=player.index(batsman)+1
            result.batsman[index]='player'+str(n)
            
        if non_striker in player:
            n = player.index(non_striker)+1
            result.non_striker[index]='player'+str(n)
        else:
            player.append(non_striker)
            n=player.index(non_striker)+1
            result.non_striker[index]='player'+str(n)
    else:
        id=id1
        inning=inning1
        player.clear()
        player.append(result.batsman[index])
        player.append(result.non_striker[index])
        
        n=player.index(batsman)+1
        result.batsman[index]='player'+str(n)
            
        n=player.index(non_striker)+1
        result.non_striker[index]='player'+str(n)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
# calculate number of wickets gone
 
# fill null value with 0
result.wicket_kind = result.wicket_kind.fillna(0)

wickets = []
id = 1
inning = 1
wicket = 0
for id1, inning1, wckt in zip(result.id, result.inning, result.wicket_kind):
  if (id==id1 and inning==inning1):
    if wckt==0 :
      wickets.append(wicket)
    else:
      wicket+=1
      wickets.append(wicket)
  else:
    id = id1
    inning = inning1
    wicket = 0
    wickets.append(wicket)

result['wickets'] = wickets

E:\Anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
result.columns

Index(['city', 'dates', 'host_team', 'id', 'player_of_match', 'result',
       'season', 'toss_decision', 'toss_winner', 'venue', 'visiting_team',
       'winner', 'ball', 'batsman', 'batsman_runs', 'batting_team', 'bowler',
       'bowling_team', 'extras_runs', 'non_striker', 'over', 'total_runs',
       'wicket', 'wicket_fielders', 'wicket_kind', 'wicket_player_out',
       'batting_team_won%', 'bowling_team_won%', 'final_score', 'inning',
       'number_of_time_batting_team_win', 'number_of_time_bowling_team_win',
       'score', 'wickets'],
      dtype='object')

In [24]:
# remove unnecessary columns
necessary_columns = ['id', 'inning', 'batting_team', 'bowling_team','batting_team_won%','bowling_team_won%','ball','over','venue',
       'batsman', 'non_striker', 'season','toss_winner', 'toss_decision',  'winner','score', 'wickets', 'final_score','number_of_time_batting_team_win','number_of_time_bowling_team_win']
dataset = result[necessary_columns]
dataset

,id,inning,batting_team,bowling_team,batting_team_won%,bowling_team_won%,ball,over,venue,batsman,non_striker,season,toss_winner,toss_decision,winner,score,wickets,final_score,number_of_time_batting_team_win,number_of_time_bowling_team_win
0,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,51.578947,47.643979,1,0,M Chinnaswamy Stadium,player1,player2,2008,Royal Challengers Bangalore,field,Kolkata Knight Riders,1,0,222,11,8
1,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,51.578947,47.643979,2,0,M Chinnaswamy Stadium,player2,player1,2008,Royal Challengers Bangalore,field,Kolkata Knight Riders,1,0,222,11,8
2,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,51.578947,47.643979,3,0,M Chinnaswamy Stadium,player2,player1,2008,Royal Challengers Bangalore,field,Kolkata Knight Riders,2,0,222,11,8
3,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,51.578947,47.643979,4,0,M Chinnaswamy Stadium,player2,player1,2008,Royal Challengers Bangalore,field,Kolkata Knight Riders,2,0,222,11,8
4,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,51.578947,47.643979,5,0,M Chinnaswamy Stadium,player2,player1,2008,Royal Challengers Bangalore,field,Kolkata Knight Riders,2,0,222,11,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190142,802,1,Kings XI Punjab,Kolkata Knight Riders,46.808511,51.578947,1,18,Sharjah Cricket Stadium,player3,player2,2020,Kings XI Punjab,field,Kings XI Punjab,147,2,150,7,12
190143,802,1,Kings XI Punjab,Kolkata Knight Riders,46.808511,51.578947,2,18,Sharjah Cricket Stadium,player4,player2,2020,Kings XI Punjab,field,Kings XI Punjab,147,2,150,7,12
190144,802,1,Kings XI Punjab,Kolkata Knight Riders,46.808511,51.578947,3,18,Sharjah Cricket Stadium,player4,player2,2020,Kings XI Punjab,field,Kings XI Punjab,148,2,150,7,12
190145,802,1,Kings XI Punjab,Kolkata Knight Riders,46.808511,51.578947,4,18,Sharjah Cricket Stadium,player2,player4,2020,Kings XI Punjab,field,Kings XI Punjab,149,2,150,7,12
190146,802,1,Kings XI Punjab,Kolkata Knight Riders,46.808511,51.578947,5,18,Sharjah Cricket Stadium,player4,player2,2020,Kings XI Punjab,field,Kings XI Punjab,150,2,150,7,12

In [25]:
# check the missing values
dataset.isnull().sum()

id                                 0
inning                             0
batting_team                       0
bowling_team                       0
batting_team_won%                  0
bowling_team_won%                  0
ball                               0
over                               0
venue                              0
batsman                            0
non_striker                        0
season                             0
toss_winner                        0
toss_decision                      0
winner                             0
score                              0
wickets                            0
final_score                        0
number_of_time_batting_team_win    0
number_of_time_bowling_team_win    0
dtype: int64

In [27]:
dataset.to_csv("../data/IPL.csv",index=False)